### ISSUE TITLE
Dataset downloading needs an account that is unable to create with non-Chinese phone

### ISSUE THREAD

**Issue by xiaohong1** [ZhengyuLiang24/LFT#4]
Excellent work. It is just that the data downloading pointing to a login window needing an account. Registration to Baidu appears to be challenging using a phone with +44 code (not in the pulldown list).

**Comment by ZhengyuLiang24** [comment]
Thanks for your attention. We have uploaded the datasets on [OneDrive](https://stuxidianeducn-my.sharepoint.com/:f:/g/personal/zyliang_stu_xidian_edu_cn/EpkUehGwOlFIuSSdadq9S4MBEeFkNGPD_DlzkBBmZaV_mA?e=FiUeiv). You can try downloading again.

**Comment by xiaohong1** [comment]
Thanks so much for your swift action. The data are being downloaded smoothly. This issue is closed.
